<?php

namespace Database\Seeders;

use App\Models\Business;
use Illuminate\Database\Seeder;

class BusinessSeeder extends Seeder
{
    public function run(): void
    {
        $migasItems = [
            'Alih Kelola Kerja Blok B',
            'Komoditi Sulfur',
            'Explorasi Minyak Blok A',
            'Pengolahan Gas Alam',
            'Distribusi BBM Regional',
            'Pertambangan Batubara',
            'Energi Surya Aceh',
            'Pembangkit Listrik Gas',
            'Pengolahan Minyak Mentah',
            'Storage & Tank Farm',
            'Pipeline Transportasi Gas',
            'LNG Processing Plant',
            'Drilling Services Aceh',
            'Well Maintenance Program',
            'Seismic Survey Aceh',
            'Geothermal Exploration',
            'Biomass Energy Plant',
            'Hydro Power Aceh',
            'Wind Farm Lhokseumawe',
            'Solar Panel Installation',
            'Gas Processing Unit',
            'Oil Refinery Modernization',
            'Petrochemical Plant',
            'Lubricant Manufacturing',
            'Asphalt Production',
            'Bitumen Processing',
            'Naphtha Production',
            'Kerosene Distribution',
            'Diesel Fuel Supply',
            'Aviation Fuel Services',
            'Marine Fuel Supply',
            'LPG Distribution Network',
            'Natural Gas Pipeline',
            'CNG Station Network',
            'Hydrogen Production',
            'Carbon Capture Project',
            'Methane Recovery System',
            'Flare Gas Recovery',
            'Enhanced Oil Recovery',
            'Enhanced Gas Recovery',
            'Oil Spill Response',
            'Environmental Monitoring',
            'Waste Heat Recovery',
            'Cogeneration Plant',
            'Trigeneration System',
            'Power Purchase Agreement',
            'Energy Audit Services',
            'Energy Efficiency Program',
            'Smart Grid Implementation',
            'Micro Grid Development',
            'Battery Storage System',
            'EV Charging Network',
            'Fuel Cell Technology',
            'Biofuel Production',
            'Ethanol Manufacturing',
            'Biodiesel Processing',
            'Renewable Energy Certificate',
            'Carbon Trading Platform',
            'Emissions Monitoring',
            'Air Quality Monitoring',
            'Water Treatment Plant',
            'Desalination Project',
            'Wastewater Treatment',
            'Solid Waste Management',
            'Hazardous Waste Disposal',
            'Environmental Impact Assessment',
            'Sustainability Reporting',
            'Green Building Certification',
            'Energy Star Program',
            'ISO 14001 Certification',
            'Clean Development Mechanism',
            'Joint Implementation Project',
            'Carbon Offset Program',
            'Renewable Portfolio Standard',
            'Feed-in Tariff Program',
            'Net Metering Program',
            'Virtual Power Plant',
            'Demand Response Program',
            'Peak Shaving Service',
            'Load Balancing System',
            'Frequency Regulation',
            'Voltage Control Service',
            'Reactive Power Compensation',
            'Power Quality Monitoring',
            'Grid Stability Analysis',
            'Reliability Assessment',
            'Maintenance Scheduling',
            'Predictive Maintenance AI',
            'Digital Twin Technology',
            'IoT Sensor Network',
            'Remote Monitoring System',
            'SCADA Integration',
            'Cybersecurity for Energy',
            'Data Analytics Platform',
            'Machine Learning Optimization',
            'Cloud Computing Infrastructure',
            'Edge Computing Deployment',
        ];

        $agroItems = [
            'Perkebunan Kopi Aceh',
            'Industri Perikanan',
            'Eksport Cangkang Sawit',
            'Pengolahan Kelapa Sawit',
            'Pertanian Organik',
            'Hortikultura Modern',
            'Peternakan Ayam',
            'Budidaya Ikan Lele',
            'Perkebunan Karet',
            'Industri Kopi Arabika',
            'Pengolahan Kakao',
            'Pertanian Padi Sawah',
            'Perkebunan Nilam',
            'Industri Lada Hitam',
            'Pengolahan Cengkeh',
            'Pertanian Jagung',
            'Perkebunan Pisang',
            'Industri Ubikayu',
            'Budidaya Udang',
            'Perikanan Tangkap',
            'Pengolahan Hasil Laut',
            'Industri Susu Sapi',
            'Peternakan Kambing',
            'Perkebunan Teh',
            'Pertanian Sayuran',
            'Industri Buah-buahan',
            'Pengolahan Rempah',
            'Pertanian Organik Premium',
            'Budidaya Lele Sangkuriang',
            'Perikanan Bandeng',
            'Industri Tepung Ikan',
            'Pengolahan Rumput Laut',
            'Pertanian Madu Lebah',
            'Perkebunan Jati',
            'Industri Rotan',
            'Pertanian Tembakau',
            'Pengolahan Kopi Liberika',
            'Budidaya Ikan Gurame',
            'Perikanan Tuna',
            'Industri Keripik Pisang',
            'Pertanian Kentang',
            'Perkebunan Cabe',
            'Industri Kacang Tanah',
            'Pengolahan Bawang',
            'Pertanian Melon',
            'Budidaya Ikan Nila',
            'Perikanan Cakalang',
            'Industri Kedelai',
            'Pertanian Ubi Jalar',
            'Perkebunan Jahe',
            'Industri Kunyit',
            'Pengolahan Lengkuas',
            'Pertanian Serai',
            'Perkebunan Kemiri',
            'Industri Pala',
            'Pengolahan Vanili',
            'Pertanian Coklat Rakyat',
            'Budidaya Ikan Patin',
            'Perikanan Tongkol',
            'Industri Abon Ikan',
            'Pertanian Padi Organik',
            'Perkebunan Sawit Rakyat',
            'Industri Minyak Sawit',
            'Pengolahan Palm Kernel',
            'Pertanian Jagung Manis',
            'Budidaya Ikan Mas',
            'Perikanan Herring',
            'Industri Tahu Tempe',
            'Pertanian Kacang Hijau',
            'Perkebunan Kacang Mete',
            'Industri Minyak Atsiri',
            'Pengolahan Nilam Aceh',
            'Pertanian Jahe Merah',
            'Budidaya Ikan Sidat',
            'Perikanan Teri',
            'Industri Terasi',
            'Pertanian Padi Inpari',
            'Perkebunan Kelapa',
            'Industri Copra',
            'Pengolahan Virgin Coconut',
            'Pertanian Ubi Kayu',
            'Budidaya Ikan Baung',
            'Perikanan Belut',
            'Industri Kerupuk',
            'Pertanian Semangka',
            'Perkebunan Semangka',
            'Industri Jus Buah',
            'Pengolahan Frozen Food',
            'Pertanian Wortel',
            'Budidaya Ikan Lele Dumbo',
            'Perikanan Gurita',
            'Industri Sarden Kaleng',
            'Pertanian Bayam',
            'Perkebunan Kubis',
            'Industri Selada',
            'Pengolahan Sayuran Beku',
            'Pertanian Tomat',
            'Budidaya Ikan Hias',
            'Perikanan Salmon Lokal',
            'Industri Makanan Ringan',
            'Pertanian Cabe Rawit',
            'Perkebunan Jahe Gajah',
            'Industri Teh Herbal',
            'Pengolahan Rempah Bubuk',
        ];

        $jasaItems = [
            'KIA Ladong',
            'KEK Arun',
            'Jaringan Telekomunikasi',
            'Pengelolaan Pelabuhan',
            'Logistik & Shipping',
            'Konstruksi Gedung',
            'Pembangunan Jalan',
            'Jasa Konsultansi',
            'Pendidikan & Pelatihan',
            'Kesehatan Masyarakat',
            'Pariwisata Aceh',
            'Perhotelan Banda Aceh',
            'Restoran & Kuliner',
            'Jasa Keuangan',
            'Asuransi Syariah',
            'Perbankan Mikro',
            'Jasa Hukum',
            'Akuntansi & Audit',
            'Manajemen Properti',
            'Real Estate Development',
            'Jasa Kebersihan',
            'Pengamanan Property',
            'Jasa Catering',
            'Event Organizer',
            'Percetakan & Publishing',
            'Digital Marketing',
            'IT Consulting',
            'Software Development',
            'Cloud Services',
            'Data Center',
            'Jasa Desain Interior',
            'Arsitektur & Engineering',
            'Jasa Survey Tanah',
            'Pemetaan & GIS',
            'Jasa Laboratorium',
            'Pengujian Material',
            'Quality Control Services',
            'Jasa Transportasi',
            'Rental Kendaraan',
            'Jasa Kurir & Ekspedisi',
            'Freight Forwarding',
            'Customs Brokerage',
            'Jasa Pendidikan Online',
            'Kursus & Training',
            'Jasa Konsultansi HR',
            'Outsourcing Tenaga Kerja',
            'Jasa Pemasaran',
            'Sales & Distribution',
            'Jasa Penagihan',
            'Jasa Pengumpulan Data',
            'Jasa Penulisan Konten',
            'Jasa Terjemahan',
            'Jasa Fotografi',
            'Jasa Videografi',
            'Jasa Event Management',
            'Wedding Organizer',
            'Jasa Dekorasi',
            'Jasa Rias & Makeup',
            'Jasa Laundry',
            'Jasa Potong Rambut',
            'Jasa Spa & Wellness',
            'Jasa Gym & Fitness',
            'Jasa Kesehatan Alternatif',
            'Jasa Akupuntur',
            'Jasa Fisioterapi',
            'Jasa Home Care',
            'Jasa Baby Sitter',
            'Jasa Tukang Kebun',
            'Jasa Service AC',
            'Jasa Service Listrik',
            'Jasa Pipa Air',
            'Jasa Renovasi Rumah',
            'Jasa Cat Tembok',
            'Jasa Pindahan',
            'Jasa Packing & Moving',
            'Jasa Penyimpanan Barang',
            'Jasa Self Storage',
            'Jasa Vending Machine',
            'Jasa ATM Management',
            'Jasa Payment Gateway',
            'Jasa E-Commerce Platform',
            'Jasa Digital Payment',
            'Jasa Blockchain',
            'Jasa Cyber Security',
            'Jasa Penetration Testing',
            'Jasa Compliance Audit',
            'Jasa Risk Management',
            'Jasa Business Intelligence',
            'Jasa Data Analytics',
            'Jasa Artificial Intelligence',
            'Jasa Machine Learning',
            'Jasa Internet of Things',
            'Jasa Virtual Reality',
            'Jasa Augmented Reality',
            'Jasa 3D Printing',
            'Jasa Drone Services',
            'Jasa Satellite imagery',
            'Jasa Remote Sensing',
        ];

        $businesses = [];
        $sortOrder = 0;

        // Migas items
        foreach ($migasItems as $i => $title) {
            $businesses[] = [
                'category' => 'migas',
                'title' => $title,
                'description' => '<p>Deskripsi detail untuk ' . $title . '. Ini adalah unit bisnis yang bergerak di sektor minyak dan gas bumi yang berlokasi di Aceh.</p><p>Bidang ini memiliki potensi besar untuk perkembangan dan kontribusi terhadap perekonomian daerah.</p>',
                'tags' => json_encode(['minyak', 'gas', 'energi', 'aceh']),
                'sort_order' => $sortOrder++,
                'created_at' => now()->subDays(rand(1, 90)),
                'updated_at' => now()->subDays(rand(1, 90)),
            ];
        }

        // Agro items
        foreach ($agroItems as $i => $title) {
            $businesses[] = [
                'category' => 'agroindustri',
                'title' => $title,
                'description' => '<p>Deskripsi detail untuk ' . $title . '. Ini adalah unit bisnis yang bergerak di sektor agroindustri yang berlokasi di Aceh.</p><p>Bidang ini memiliki potensi besar untuk perkembangan dan kontribusi terhadap perekonomian daerah.</p>',
                'tags' => json_encode(['agro', 'pertanian', 'perikanan', 'aceh']),
                'sort_order' => $sortOrder++,
                'created_at' => now()->subDays(rand(1, 90)),
                'updated_at' => now()->subDays(rand(1, 90)),
            ];
        }

        // Jasa items
        foreach ($jasaItems as $i => $title) {
            $businesses[] = [
                'category' => 'jasa',
                'title' => $title,
                'description' => '<p>Deskripsi detail untuk ' . $title . '. Ini adalah unit bisnis yang bergerak di sektor jasa dan perdagangan yang berlokasi di Aceh.</p><p>Bidang ini memiliki potensi besar untuk perkembangan dan kontribusi terhadap perekonomian daerah.</p>',
                'tags' => json_encode(['jasa', 'perdagangan', 'aceh']),
                'sort_order' => $sortOrder++,
                'created_at' => now()->subDays(rand(1, 90)),
                'updated_at' => now()->subDays(rand(1, 90)),
            ];
        }

        // Insert in chunks
        foreach (array_chunk($businesses, 50) as $chunk) {
            Business::insert($chunk);
        }

        $this->command->info('Business seeder completed: ' . count($businesses) . ' items inserted.');
    }
}
